---
title: "Week 5 Practice"
author: "Bret"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      error = TRUE)
                    
library(tidyverse)
library(lubridate)
library(kableExtra)
library(readxl)
source("../../scripts/viridis.R")
```

### Read the 2018 airport data

```{r read-data}
## Three-letter airport codes
airport_codes = c("DEN", "JFK", "LAX", "MSP", "ORD", "SFO")

## use purrr::read_dfr() to read each csv file
##   and bind their rows into a single output data frame
awt = map_dfr(airport_codes, ~{
  filename = str_c("../../data/", .x, "-2018.csv")
  return( read_csv(filename) )
})
```


```{r}
## eliminate some columns
awt_1 = awt %>% 
  select(-contains("_wait"), -all_total, -all_flights, -all_booths)

## Show the column names
names(awt_1)

## Reshape the data by pivoting longer

awt_long = awt_1 %>%
  pivot_longer(cols = starts_with("all_"),
               names_to = "wait_interval",
               values_to = "n")

## Show the column names of the reshaped data frame
names(awt_long)
```

#### pivot_wider()

```{r}
awt_sum = awt %>% 
  group_by(airport, hour) %>% 
  summarize(mean_wait_time = sum(all_avg_wait * all_total) / sum(all_total))

awt_sum %>% 
  head(n = 10)
  
```

```{r}
## pivot_wider example
awt_sum_wide = awt_sum %>% 
  pivot_wider(names_from = airport, values_from = mean_wait_time) %>% 
  arrange(hour)

awt_sum_wide %>% 
  print(n = Inf, width = Inf)
```


### fill-in example

```{r}
## First total arrivals by airport and hour
awt_arrivals = awt %>% 
  group_by(airport, hour) %>% 
  summarize(flights = sum(all_flights))

dim(awt_arrivals)

awt_arrivals %>% 
  print(n = 30)
```


### Live pivot_wider()

```{r}
arrivals_wide = awt_arrivals %>% 
  pivot_wider(names_from = airport,
              values_from = flights,
              values_fill = 0) %>% 
  arrange(hour)
```

```{r, echo = FALSE}
arrivals_wide

arrivals_wide %>% 
  kable() %>% 
  kable_styling( position = "left", full_width = FALSE,
                 bootstrap_options = c("striped"))
```

### Obesity Data

```{r read-one}
male_05_17 =  read_excel(
  "../../data/Obesity+Prevalence+by+ZIP+Code+and+Age+Group,+Males.xlsx",
  sheet=3, skip=5, na=".")

str(male_05_17)
```


```{r one-reformat}
male_05_17 = male_05_17 %>%
  select(starts_with("ZIP"),
         starts_with("Number"),
         starts_with("Population")) %>%
  rename(zip = starts_with("ZIP"),
         obese = ends_with("Obesity"),
         n = ends_with("BMI"),
         pop = starts_with("Population")) %>%
  mutate(sex = "male") %>%
  mutate(age = "5-17")

head(male_05_17)
```



```{r obesity-info}
temp = tibble(
  sheet = 3:7,
  age = c("05-17","18-34","35-54","55-74","75+"))

obesity_info = expand_grid(sex = c("Females", "Males"),
                           sheet = 3:7) %>% 
  left_join(temp, by = "sheet")

obesity_info
```



```{r obesity-read-all}
obesity = obesity_info %>% 
  pmap_dfr(~{
    str_glue("../../data/Obesity+Prevalence+by+ZIP+Code+and+Age+Group,+{..1}.xlsx") %>% 
      read_excel(sheet = ..2, skip = 5, na = ".") %>% 
      select(starts_with(c("ZIP","Number","Population"))) %>% 
      rename(zip = starts_with("ZIP"),
             obese = ends_with("Obesity"),
             n = ends_with("BMI"),
             pop = starts_with("Population")) %>% 
      mutate(sex = ..1, age = ..3)
  }) %>% 
  as_tibble() %>% 
  mutate(sex = recode(sex,
                      "Females" = "female",
                      "Males" = "male")) %>% 
  relocate(zip, sex, age)
```



```{r}
obesity = obesity %>% 
  mutate(obese_pop = pop * (obese/n),
         non_obese_pop = pop * (1 - obese/n))

head(obesity)
```
```{r}

```

